language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - /^release-.*$/
  - master
notifications:
  email:
    recipients:
    - j.bernal@upm.es
services:
  - mongodb
script:
#Test unitario y de integracion en perfil DEV, con covertura
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

# SONAR
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR

# Deploy https://betca-tpv-spring.herokuapp.com/api/v0/swagger-ui.html
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
